# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app04', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(choices=[(2, '女'), (3, '人妖'), (1, '男')], verbose_name='性别'),
        ),
    ]
