# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=132)),
                ('fans', models.ManyToManyField(to='app01.User', verbose_name='粉丝')),
            ],
        ),
    ]
