# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20171116_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=132, null=True, verbose_name='评论内容')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Comment')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='fans',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
