# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='department',
            new_name='userType',
        ),
    ]
