# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj01', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='tel',
            field=models.IntegerField(max_length=12),
        ),
    ]
