# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj01', '0004_auto_20171027_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='tel',
            field=models.IntegerField(),
        ),
    ]
