# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj01', '0005_auto_20171027_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='tel',
        ),
        migrations.AlterField(
            model_name='author',
            name='tel',
            field=models.CharField(max_length=32),
        ),
    ]
