# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20171107_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=182, verbose_name='标题')),
            ],
        ),
        migrations.AddField(
            model_name='permission',
            name='code',
            field=models.CharField(blank=True, max_length=32, verbose_name='代码'),
        ),
        migrations.AddField(
            model_name='permission',
            name='groups',
            field=models.ForeignKey(blank=True, default=222, on_delete=django.db.models.deletion.CASCADE, to='rbac.Group'),
            preserve_default=False,
        ),
    ]
