# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20171122_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article2tag',
            options={'verbose_name_plural': '文章标签关系表'},
        ),
        migrations.AlterModelOptions(
            name='sitearticlecategory',
            options={'verbose_name_plural': '站点文章分类'},
        ),
        migrations.AlterModelOptions(
            name='sitecategory',
            options={'verbose_name_plural': '站点分类'},
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
    ]
