# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20171123_1708'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articleup',
            unique_together=set([('user', 'article')]),
        ),
        migrations.AlterUniqueTogether(
            name='commentup',
            unique_together=set([('user', 'comment')]),
        ),
    ]
