# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20171124_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
    ]
